name: CI
on: [push]

env:
  CARGO_TERM_COLOR: always

# https://alican.codes/rust-github-actions
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest Rust toolchain for x86_64 linux
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-unknown-linux-gnu
          toolchain: stable
          default: true
          override: true

      - name: Test
        run: cargo test --release

      - name: Build
        run: cargo build --release && mv target/release/jear jear-x86_64-linux

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: builds
          retention-days: 1
          path: jear-x86_64-linux
